version: "3"

services:
    app:
        build:
            context: ./private-backend
        ports:
            - "7000:8888"
        volumes:
            - ./private-backend/app:/private-backend/app
        command: >
            python3 /private-backend/app/web.py --db_host=db
        environment: 
            - DB_HOST=db
            - DB_NAME=app
            - DB_USER=postgres
            - DB_PASS=supersecretpassword
        depends_on: 
            - db
    
    
    db:
        image: postgres:10-alpine
        environment: 
            - POSTGRES_DB=app
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=supersecretpassword
        