# Generated by Django 3.2.6 on 2021-08-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='theme',
            field=models.CharField(default='None of the above', max_length=50),
        ),
    ]
