# Generated by Django 3.2.6 on 2021-08-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_snapshot_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot',
            field=models.ImageField(upload_to='snapshot'),
        ),
    ]
