# Generated by Django 3.2.6 on 2021-08-10 07:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_snapshot_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot',
            field=models.ImageField(default='snapshot/test.png', upload_to=core.models.upload_to),
        ),
    ]
