# Generated by Django 3.2.6 on 2021-08-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_snapshot_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='snapshot',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
