# Generated by Django 3.2.6 on 2021-08-10 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210810_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
